### ISSUE TITLE
Please change the name or give credit !

### ISSUE THREAD

**Issue by LinxGem33** [fusion809/OSX-Arc-White#3]
@fusion809 

Appreciate you using the OSX-Arc-White theme I'm the original creator of the theme which was forked by umayanga who was the creator of the apple arc theme and in turn what you are now using.

I'm not concerned with you using the theme but your using the name which is not good practice without either crediting the original authors or changing the name all together.

So could you please either credit the original author (i.e LinxGem33 which is me and horst3180) or change the name as it becomes confusing for users to know which is the original project and author   
i would greatly appreciate it.

**Kind regards** LinxGem33

**Comment by fusion809** [comment]
Does 1c43206 fix your dilemma?

**Comment by LinxGem33** [comment]
@fusion809 

I think your miss understanding me !

change the name from osx-arc-white to something of your choosing its open source so your free to with the code what you like but its good practice to not use the same name of the original project thats all nothing big to change just the name my friend.

**kind regards** LinxGem33

**Comment by fusion809** [comment]
But the name of this issue is "Please change the name **or** give credit !" with **or** being the key word. I gave you credit in the LICENSE.md file, so that OR statement was satisfied...

**Comment by LinxGem33** [comment]
your a funny guy or girl

i was asking you in good spirit but unfortunately you wasn't listening Ive said all i need to say now.

regards
